<?php

/**
 * Stephen Lake - Iveri API Wrapper Package
 *
 * @author Stephen Lake <stephen-lake@live.com>
 */

namespace StephenLake\Iveri\Objects;

class TransactionResultCodes {

  public static function getMessage($errorCode, $fallbackMessage = NULL) {

    if (!isset(self::$errorCodeMapping[$errorCode])) {
      if (!is_null($fallbackMessage)) {
        return $fallbackMessage;
      }
      
      return self::$errorCodeMapping['X001'];
    }

    return self::$errorCodeMapping[$errorCode];
	}

  private static $errorCodeMapping = [

    // Package/Custom Defined Responses
    'X000' => 'There was an error communicating with the payment gateway. Please try again in a minute.',
    'X001' => 'An unexpected internal network error has occurred.',

    // Validation Responses
    '1001' => 'Gateway Required An incorrect gatewayid was specified. The Gateway IDcorresponds to the bank / acquirer that the merchant account islinked to.',
    '1002' => 'MerchantID Required.',
    '1003' => 'Invalid Merchant UID An incorrect MerchantID was specified. This will identify thecustomer account on the Iveri platform.',
    '1004' => 'ApplicationUIDRequired. An ApplicationID was not specified. Please ensure that a validApplicationID is entered. Your ApplicationID can be retrievedfrom the integration email or from the Iveri Web Console.Refer to Data Element 3',
    '1005' => 'InvalidApplicationUIDAn incorrect Application ID was specified. This will identify theApplication that is linked to the customer account on the Iveriplatform. Refer to Data Element 3',
    '1006' => 'Action Required An Action was not specified. Please enter one of the followingActions: (1,2,3,4). Refer to Data Element 4',
    '1007' => 'Invalid Action An Incorrect Action was specified. A valid Action is one of thefollowing: (1,2,3,4). Refer to Data Element 4',
    '1008' => 'Invalid TransactionIndexAn incorrect TransactionIndex was specified. Please ensure that avalid transaction index was entered. Refer to Data Element 5',
    '1009' => 'Terminal Required A Terminal was not specified. Please check that you haveentered a Terminal. Refer to Data Element 6',
    '1010' => 'Invalid Terminal An invalid terminal was specified. A terminal is an alphanumericstring with a minimum of 4 and a maximum of 16 characters.Refer to Data Element 6',
    '1011' => 'Mode Required A Mode was not entered. Please ensure that a mode has beenentered in order to complete the transaction. Refer to DataElement 7',
    '1012' => 'Invalid Mode An incorrect Mode was specified. Please enter Mode 0 for testor Mode 1 for Live. Refer to Data Element 7',
    '1013' => 'MerchantReferenceRequiredA MerchantReference was not entered. The MerchantReferncelinks the payment to a specific client. Refer to Data Element 8',
    '1014' => 'InvalidMerchantReferenceAn incorrect MerchantReference was entered. AMerchantReference is an alphanumeric string containing aminimum of 4 to 16 Characters. A MerchantReference cannotcontain symbols or have spaces. Refer to Data Element 8',
    '1015' => 'Amount Required An Amount was not entered. Please ensure that a valid Amount is entered. Refer to Data Element 9',
    '1016' => 'Zero Amount A Zero Amount was entered. An Amount indicates the value ofthe transaction that needs to be processed. Refer to DataElement 9',
    '1017' => 'Invalid Amount An incorrect Amount was entered. The amount that was enteredneeds to be entered in the following format: 50.00. Refer toData Element 9',
    '1018' => 'Currency Required A Currency was not specified. Refer to Data Element 10',
    '1019' => 'TransactionIndexrequiredA TransactionIndex is required. The transaction index is requiredin order to process the transaction. Refer to Data Element 5',
    '1020' => 'CardType required An incorrect type was inserted. Enter the correct Card Type tocomplete the transaction. Refer to Data Element 12',
    '1021' => 'Invalid CardType An invalid Card Type was specified. A valid Card Type is anumber from 1 to 4. Refer to Data Element 12',
    '1022' => 'CardNumberrequiredThe Card Number is required. A card number needs to bespecified in order to complete the transaction. Refer to DataElement 14',
    '1023' => 'Invalid Currency An invalid Currency was specified. Describe requirements ofISO4217. Refer to Data Element 10',
    '1024' => 'Invalid CardNumber An incorrect Card Number was specified. The correct CardNumber is required as it gets sent to the bank for Authorization.Refer to Data Element 14',
    '1025' => 'CCVNumber required This Credit Card Verification Number is required. Please insert acorrect Credit Card Verification Number. Refer to Data Element16',
    '1026' => 'Invalid CCVNumber An incorrect Card Verification Number has been entered. Referto Data Element 16',
    '1027' => 'ExpiryMonthRequiredAn Expiry Month is required. The Expiry Month needs to beentered in order to complete this transaction. Refer to DataElement 17',
    '1028' => 'ExpiryYear Required An Expiry Year is required. The Expiry Year needs to be entered inorder to complete the transaction. Refer to Data Element 18',
    '1029' => 'Invalid ExpiryMonth An incorrect Expiry Month was entered. The correct ExpirationMonth of the credit card needs to entered in order to completethe transaction. Refer to Data Element 17',
    '1030' => 'Invalid ExpiryYear An incorrect Expiry Year was entered. The correct Expiration yearof the credit card need to entered in order to complete thetransaction. Refer to Data Element 18',
    '1031' => 'Past Expiry Date The expiry date is in the past. The expiration date entered wasinvalid. Please ensure that a valid expiration date is entered tocomplete the transaction. Refer to Data Element 90',
    '1032' => 'Account TypeRequiredAn account type was not entered. Please ensure that an accounttype is entered in order to complete the transaction. Refer toData Element 13',
    '1033' => 'Invalid Account Type An incorrect Account Type was entered. The Account Type is anumber between 1 and 3 and it needs to be specified in order tocomplete the transaction. Refer to Data Element 13',
    '1034' => 'Card Holder Required A Card Holder was not entered. Please ensure that a Card Holderis entered to complete the transaction. Refer to Data Element 15',
    '1035' => 'Invalid Card Holder An Incorrect Card Holder was entered. The Card Holder nameneeds to be an alphanumeric string with a max length of 255characters. Refer to Data Element 15',
    '1036' => 'Invalid CCV for thiscard typeAn incorrect CVV was entered for this card type. The CVV is the 3digit number displayed at the back of the credit card. Refer toData Element 16',
    '1037' => 'Invalid Budget An incorrect budget was entered. A budget is indicated by 1 or 0.Refer to Data Element 19',
    '1038' => 'Budget PeriodRequiredA Budget period was not entered. Please ensure that a Budgetperiod is entered in order to complete the transaction. Refer toData Element 19',
    '1039' => 'Invalid Budget Period An invalid Budget period was entered. A budget period isbetween 1 - 24 months. Refer to Data Element 20',
    '1040' => 'Amount Required A Cashback amount was not entered. Please ensure that aCashback amount has been entered. Refer to Data Element 11',
    '1041' => 'Zero Amount A zero Cashback amount is not allowed. The cashback amountneeds to have a value. Please indicate the Cashback amount tocomplete the transaction. Refer to Data Element 11',
    '1042' => 'Invalid Amount An invalid cashback Amount was specified. {Describerequirements of ISO4217}. Refer to Data Element 11',
    '1043' => 'Invalid Authorisation An incorrect authorization was entered. Please ensure that avalid authorization number was entered in order to completethe transaction. Refer to Data Element 21',
    '1044' => 'Invalid Budget An incorrect budget was entered. Please ensure that one of thefollowing budget numbers are entered: 0 or 1. Refer to DataElement 19',
    '1045' => 'AuthorisationNumberRequiredAn authorisation number was not entered. The authorisationnumber is required to complete this transaction. Refer to DataElement 21',
    '1046' => 'PIN Required A PIN was not entered. Please ensure that a PIN is entered. Referto Data Element 22',
    '1047' => 'Invalid PIN An invalid PIN was entered. Please specify a valid PIN. Refer toData Element 22',
    '1048' => 'eCommerceIndicatorRequiredAn eCommerceindicator was not entered. Please ensure that aneCommerceIdicator has been entered. Refer to Data Element 24',
    '1049' => 'InvalideCommerceIndicatorAn Incorrect eCommerceIndicator was entered. Please anter avalid eCommerce indicator. Refer to Data Element 24',
    '1050' => 'verifiedByVisaXIDRequiredA verifiedByVisaXID was not specified. Please check that youhave entered a verifiedByVisaXID. Refer to Data Element 25',
    '1051' => 'InvalidverifiedByVisaXIDAn invalid verifiedByVisaXID was specified. A validverifiedByVisaXID was expected. Refer to Data Element 25',
    '1052' => 'verifiedByVisaCAVVRequiredA verifiedByVisaCAVV was not specified. Please check that youhave entered a verifiedByVisaCAVV. Refer to Data Element 26',
    '1053' => 'InvalidverifiedByVisaCAVVAn invalid verifiedByVisaCAVV was specified. A validverifiedByVisaCAVV was expected. Refer to Data Element 26',
    '1054' => 'secureCodeUCAFRequiredA secureCodeUCAF was not specified. Please check that youhave entered a secureCodeUCAF.',
    '1055' => 'InvalidsecureCodeUCAFAn invalid secureCodeUCAF was specified. A validsecureCodeUCAF was expected.',
    '1056' => 'SSL Required This service must be called using SSL (https).',
    '1057' => 'UCI Required A UCI was not specified. Please check that you have entered aUCI.',
    '1059' => 'IP Address Required A IP Address was not specified. Please check that you haveentered a IP Address.',
    '1060' => 'Invalid Public IPAddressAn invalid Public IP Address was specified. This will be returned ifthe IP Address you are coming from is invalid or is within a local(127.0.0.1, etc) IP range.',
    '1061' => 'Shipping CountryCode RequiredA Shipping Country Code was not specified. Please check thatyou have entered a Shipping Country Code.',
    '1062' => 'Invalid ShippingCountry Code FormatAn invalid Shipping Country Code was specified. A valid ShippingCountry Code is expected - 2 alphabetical characters.',
    '1063' => 'InvalidPurchaseItemsIDAn invalid PurchaseItemsID was specified. I',
    '1064' => 'Invalid GateWayID An invalid GateWayID was specified.',
    '1065' => '3D Secure failed Cardholder enrolled, successful authentication, unsuccessfulsignature verification.',
    '1066' => '3D Secure failed Cardholder enrolled, unsuccessful authentication, successfulsignature verification.',
    '1067' => 'verifiedByVisaXIDRequiredverifiedByVisaXID required when eCommerceIndicator = 05.',
    '1068' => 'verifiedByVisaCAFFRequiredverifiedByVisaCAFF required when eCommerceIndicator = 05.',
    '1078' => 'Invalid Date From An invalid Date From value was specified. This needs to be in theformat: yyyy/MM/dd hh:mm“yyyy/MM/dd hh:mm”',
    '1080' => 'Invalid Date To An invalid Date To value was specified. This needs to be in theformat: yyyy/MM/dd hh:mm',
    '1081' => 'Incomplete SearchCriteriaNeither a TransactionIndex nor a date range was specified. Atleast one of these values are required.',
    '1090' => 'Carrier NameRequiredA carrier name was not specified. Please check that you haveentered a carrier name.',
    '1091' => 'Invalid Carrier Name An invalid carrier name was specified. A valid carrier name isexpected - an...19.',
    '1092' => 'Ticket Nr Required A ticket nr was not specified. Please check that you have entereda ticketnr.',
    '1093' => 'Invalid Ticket Nr An invalid Ticket Nr was specified. A valid ticket nr is expected -an...15.',
    '1094' => 'Plan Nr Required A plan nr was not specified. Please check that you have entereda plan nr.',
    '1095' => 'Invalid Plan Nr An invalid plan nr was specified. A valid plan nr is expected - an2.',
    '1096' => 'Invoice Nr Required An invoice nr was not specified. Please check that you haveentered an invoice nr.',
    '1097' => 'Invalid Invoice Nr An invalid invoice nr was specified. A valid invoice nr is expected- an6.',
    '1098' => 'Passenger NameRequiredA passenger name was not specified. Please check that you haveentered a passenger name.',
    '1099' => 'Invalid PassengerNameAn invalid passenger name was specified. A valid passengername is expected - ans...29.',
    '1100' => 'Customer RefRequiredA customer ref was not specified. Please check that you haveentered a customer ref.',
    '1101' => 'Invalid Customer Ref An invalid customer ref was specified. A valid customer ref isexpected - ans...20.',
    '1102' => 'Travel Agency CodeRequiredA travel agency code was not specified. Please check that youhave entered a travel agency code.',
    '1103' => 'Invalid Travel AgencyCodeAn invalid travel agency code was specified. A valid travel agencycode is expected - an8.',
    '1104' => 'Ticket Agency NameRequiredA ticket agency name was not specified. Please check that youhave entered a ticket agency name.',
    '1105' => 'Invalid Ticket AgencyNameAn invalid ticket agency name was specified. A valid ticketagency name is expected - an...25.',
    '1106' => 'Ticket Issue AddressRequiredA ticket issue address was not specified. Please check that youhave entered a ticket issue address.',
    '1107' => 'Invalid Ticket IssueAddressAn invalid ticket issue address was specified. A valid ticket issueaddress is expected - ans...16.',
    '1108' => 'Date Ticket IssueRequiredA date ticket issue was not specified. Please check that you haveentered a date ticket issue.',
    '1109' => 'Invalid Date TicketIssueAn invalid date ticket issue was specified. A valid date ticketissue is expected - YYYYMMDD.',
    '1110' => 'Amount Total FareRequiredAn amount total fare was not specified. Please check that youhave entered an amount total fare.',
    '1111' => 'Invalid Amount TotalFareAn invalid amount total fare was specified. A valid amount totalfare is expected - n12.',
    '1112' => 'Amount Total FeesRequiredAn amount total fees was not specified. Please check that youhave entered an amount total fees.',
    '1113' => 'Invalid Amount TotalFeesAn invalid amount total fees was specified. A valid amount totalfees is expected - n12.',
    '1114' => 'Amount Total TaxesRequiredAn amount total taxes was not specified. Please check that youhave entered an amount total taxes.',
    '1115' => 'Invalid Amount TotalTaxesAn invalid amount total taxes was specified. A valid amount totaltaxes is expected - n12.',
    '1116' => 'Amount OriginalInvoice RequiredAn amount original invoice was not specified. Please check thatyou have entered an amount original invoice.',
    '1117' => 'Invalid AmountOriginal InvoiceAn invalid amount orignal invoice was specified. A valid amountoriginal invoice is expected - n12.',
    '1118' => 'Original CurencyCode RequiredAn original currency code was not specified. Please check thatyou have entered an original currency code.',
    '1119' => 'Invalid OriginalCurrency CodeAn invalid original currency code was specified. A valid originalcurrency code is expected - n3.',
    '1120' => 'Leg Nr Required A leg nr was not specified. Please check that you have entered aleg nr.',
    '1121' => 'Invalid Leg Nr An invalid leg nr was specified. A valid leg nr is expected - n2.',
    '1122' => 'Leg Carrier CodeRequiredA leg carrier code was not specified. Please check that you haveentered a leg carrier code.',
    '1123' => 'Invalid Leg CarrierCodeAn invalid leg carrier code was specified. A valid leg carrier codeis expected - an2.',
    '1124' => 'Leg Flight NrRequiredA leg flight nr was not specified. Please check that you haveentered a leg flight nr.',
    '1125' => 'Invalid Leg Flight Nr An invalid leg flight nr was specified. A valid leg flight nr isexpected - ans5.',
    '1126' => 'Leg DepartureAirport RequiredA leg departure airport was not specified. Please check that youhave entered a leg departure airport.',
    '1127' => 'Invalid Leg DepartureAirportAn invalid leg departure airport was specified. A valid legdeparture airport is expected - an5.',
    '1128' => 'Leg Stopover CodeRequiredA leg stopover code was not specified. Please check that youhave entered a leg stopover code.',
    '1129' => 'Invalid Leg StopoverCodeAn invalid leg stopover code was specified. A valid leg stopovercode is expected - an1.',
    '1130' => 'Leg Destination CodeRequiredA leg destination code was not specified. Please check that youhave entered a leg destination code.',
    '1131' => 'Invalid LegDestination CodeAn invalid leg destination code was specified. A valid legdestination code is expected - an5.',
    '1132' => 'Leg Date Of TravelRequiredA leg date of travel was not specified. Please check that you haveentered a leg date of travel.',
    '1133' => 'Invalid Leg Date OfTravelAn invalid leg date of travel was specified. A valid leg date oftravele is expected - YYYYMMDD.',
    '1134' => 'Leg Departure TimeRequiredA leg departure time was not specified. Please check that youhave entered a leg departure time.',
    '1135' => 'Invalid Leg DepartureTimeAn invalid leg departure time was specified. A valid leg departuretime is expected - HHMM.',
    '1136' => 'Leg Departure TimeSegment CodeRequiredA leg departure time segment code was not specified. Pleasecheck that you have entered a leg departure time segment code.',
    '1137' => 'Invalid Leg DepartureTime Segment CodeAn invalid leg departure time segment code was specified. Avalid leg departure time segment code is expected - as1.',
    '1138' => 'Leg Arrival TimeRequiredA leg arrival time was not specified. Please check that you haveentered a leg arrival time.',
    '1139' => 'Invalid Leg ArrivalTimeAn invalid leg arrival time was specified. A valid leg arrival time isexpected - HHMM.',
    '1140' => 'Leg Arrival TimeSegment CodeRequiredA leg arrival time segment code was not specified. Please checkthat you have entered a leg arrival time segment code.',
    '1141' => 'Invalid Leg ArrivalTime Segment CodeAn invalid leg arrival time segment code was specified. A validleg arrival time segment code is expected - as1.',
    '1142' => 'Leg Class Of TravelRequiredA leg class of travel was not specified. Please check that youhave entered a leg class of travel.',
    '1143' => 'Invalid Leg Class OfTravelAn invalid leg class of travel was specified. A valid leg class oftravel is expected - an2.',
    '1144' => 'Leg Coupon NrRequiredA leg coupon nr was not specified. Please check that you haveentered a leg coupon nr.',
    '1145' => 'Invalid Leg CouponNrAn invalid leg coupon nr was specified. A valid leg coupon nr isexpected - ans1.',
    '1146' => 'Leg ConjunctionTicket Nr RequiredA leg conjunction ticket nr was not specified. Please check thatyou have entered a leg conjunction ticket nr.',
    '1147' => 'Invalid LegConjunction Ticket NrAn invalid leg conjunction ticket nr was specified. A valid legconjunction ticket nr is expected - an...15.',
    '1148' => 'Leg Exchange TicketNr RequiredA leg exchange ticket nr was not specified. Please check that youhave entered a leg exchange ticket nr.',
    '1149' => 'Invalid Leg ExchangeTicket NrAn invalid leg exchange ticket nr was specified. A valid legexchange ticket nr is expected - an...15.',
    '1150' => 'Leg Fare Basis CodeRequiredA leg fare basis code was not specified. Please check that youhave entered a leg fare basis code.',
    '1151' => 'Invalid Leg Fare BasisCodeAn invalid leg fare basis code was specified. A valid leg fare basiscode is expected - an...15.',
    '1152' => 'Leg Amount FareRequiredA leg amount fare was not specified. Please check that you haveentered a leg amount fare.',
    '1153' => 'Invalid Leg AmountFareAn invalid leg amount fare was specified. A valid leg amount fareis expected - n12.',
    '1154' => 'Leg Amount FeesRequiredA leg amount fees was not specified. Please check that you haveentered a leg amount fees.',
    '1155' => 'Invalid Leg AmountFeesAn invalid leg amount fees was specified. A valid leg amount feesis expected - n12.',
    '1156' => 'Leg Amount TaxesRequiredA leg amount texes was not specified. Please check that youhave entered a leg amount texes.',
    '1157' => 'Invalid Leg AmountTaxesAn invalid leg amount taxes was specified. A valid leg amounttexes is expected - n12.',
    '1158' => 'Leg AmountDeparture TaxRequiredA leg amount departure tax was not specified. Please check thatyou have entered a leg amount departure tax.',
    '1159' => 'Invalid Leg AmountDeparture TaxAn invalid leg amount departure tax was specified. A valid legamount departure tax is expected - n12.',
    '1160' => 'Leg Endorsements OrRestrictions RequiredA leg endorsements or restrictions was not specified. Pleasecheck that you have entered a leg endorsements or restrictions.',
    '1161' => 'Invalid LegEndorsements OrRestrictionsAn invalid leg endorsements or restrictions was specified. A validleg endorsements or restrictions is expected - ans...20.Initiating Response 2001 Invalid Gateway The specified gateway does not exist or is invalid. Please ensurethat one of the following Gateways are entered:01,21,22,23,24,25,26. Refer to Data Element 1Initiating Response 2002 MerchantID iscancelled.The MerchantID entered is cancelled. Contact Iveri toreactivate Refer to Data Element 2Initiating Response 2003 ApplicationID doesnot existThe ApplicationID entered does not exist.',

    // Initiating Responses
    '2001' => 'Invalid Gateway The specified gateway does not exist or is invalid. Please ensure that one of the following Gateways are entered: 01,21,22,23,24,25,26. Refer to Data Element 1',
    '2002' => 'MerchantID is cancelled. The MerchantID entered is cancelled. Contact Iveri to reactivate Refer to Data Element 2',
    '2003' => 'ApplicationID does not exist The ApplicationID entered does not exist. Please ensure that a valid ApplicationID is entered. Refer to Data Element 3',
    '2004' => 'TransactionIndex not found The transactionIndex entered does not exist. Please ensure that a valid TransactionIndex is entered to complete the transation. Refer to Data Element 5',
    '2005' => 'Duplicate Merchant Reference A duplicate merchant reference was found. Please ensure that a Unique MerchantReference is entered. Refer to Data Element 8',
    '2006' => 'Can’t Credit without Debit A credit action cannot be implemented without a debit action on a transaction. Refer to Data Element 4',
    '2007' => 'ReverseAuthorisation Already Performed A ReverseAuthorisation action has already been implemented for this transaction. Only 1 action can be made on this transaction. Refer to Data Element 4',
    '2008' => 'Debit Already Performed A Debit action has already been implemented for this transaction. A ReverseAuthorisation cannot be performed on a settled transaction.',
    '2009' => 'Credit Already Performed A Credit action has already been implemented for this transaction. No more actions can be performed on this Transaction',
    '2010' => 'Authorisation Expected Authorisation Action has not yet been performed. All transactions have to begin with the authorisation action 1. See data element 4',
    '2011' => 'Debit Already performed A debit action has already been performed on this transaction. An action 3 cannot be performed twice on the same transaction.',
    '2012' => 'Authorisation Already performed An authorisation action has already been performed on this transaction. An action cannot be performed twice on the same transaction',
    '2013' => 'Budget must preceed transaction Only a successful authorization and budget can preced a budget reversal.',
    '2014' => 'Authorise must preceed transaction Only a successful AUTHORISEREFUND can preced a AUTHORISEREFUNDREVERSAL',
    '2015' => 'Authorise must preceed transaction Only a successful AUTHORISEREFUND can preced a REFUND',
    '2016' => 'Refund must preceed transaction Only a successful AUTHORISEREFUND and REFUND can preced a REFUNDREVERSAL',
    '2017' => 'Authorise must preceed transaction Only a successful AUTHORISECASHADVANCE can preced an AUTHORISECASHADVANCEREVERSAL',
    '2018' => 'Authorise must preceed transaction Only a successful AUTHORISECASHADVANCE can preced a CASHADVANCE',
    '2019' => 'Refund must preceed transaction Only a successful AUTHORISECASHADVANCE and CASHADVANCE can preced a CASHADVANCEREVERSAL',
    '2020' => 'Incorrect Relationship An Incorrect Relationship with Gateway, Application and Merchant. Please ensure that the MerchantID, ApplicationID and gateway that was entered are correct',
    '2021' => 'Invalid Shipping Country Code An invalid Shipping Country Code was specified. Please provide a valid shipping country code. Refer to Data Element 30',
    '2022' => 'Purchase must preceed transaction Only a successful AUTHORISEPURCHASE and PURCHASE can preceed a VOID.',
    '2023' => 'Purchase Reversal must preceed transaction Only a successful AUTHORISEPURCHASE, PURCHASE and PURCHASEREVERSAL can preceed a VOID.',
    '2024' => 'Purchase must preceed transaction Only a successful PURCHASE with auth code can preceed a VOID.',
    '2025' => 'Credit must preceed transaction Only a successful CREDIT can preceed a VOID.',
    '2050' => 'Incorrect Decimal Length An incorrect',

    // Security Response
    '4001' => 'Mode Denied Mode Denied. Application Status is developing. Please contact Iveri.',
    '4002' => 'Invalid Mode / Credit Card Invalid Card for Live Mode. Test Card not allowed to be used Live Mode. Refer to Data Element 7',
    '4003' => 'Merchant Inactive Merchant ID is Inactive. Refer to Data Element 2',
    '4004' => 'Merchant Suspended Merchant ID is Suspended. Refer to Data Element 2',
    '4005' => 'Merchant Removed Merchant ID has been Removed. Refer to Data Element 2',
    '4006' => 'Application Inactive Application ID is Inactive. Refer to Data Element 3',
    '4007' => 'Application Suspended Application ID is Suspended. Refer to Data Element 3',
    '4008' => 'Application Removed Application ID has been Removed. Refer to Data Element 3',
    '4009' => 'Source IP Address Invalid The IP Address is not in the list of allowed IP Addresses for this Application.',
    '4010' => 'Gateway Inactive The gateway that your trying to use, has been set to inactive. Refer to Data Element 1',
    '4011' => 'Gateway Obsolete The gateway that your trying to use, is no longer in use. Refer to Data Element 1',
    '4012' => 'Currency not allowed The currency you have specified is not listed under the allowed list of currencies for your application. Refer to Data Element 10',
    '4013' => 'Invalid Currency The currency you have specified is invalid. Refer to Data Element 10',
    '4014' => 'Transaction Limit Exceeded This transaction amount exceeds the transaction limit for your application. Refer to Data Element 9',
    '4015' => 'Cumulative Transaction Limit Exceeded This transaction amount exceeds the cumulative transaction limit for your application. Refer to Data Element 9',
    '4016' => 'CardType not allowed The card type you have specified is not listed under the allowed list of card types for your application. Refer to Data Element 12',
    '4017' => 'AccountType not allowed The account type you have specified is not listed under the allowed list of account types for your application. Refer to Data Element 13',
    '4018' => 'Budget not allowed Budget transactions are not allowed for your application. Refer to Data Element 19',
    '4019' => 'eCommerceIndicator not allowed The eCommerceIndicator you have specified is not listed under the allowed list of eCommerceIndicators for your application.',

    // Bank Response
    '5001' => 'Connection to Bank could not be established.',
    '5002' => 'Declined by the Bank.',

    // Fraud Module Response
    '6001' => 'Card Number Blacklisted This transaction has been declined by BLS.',
    '6002' => 'Country Code Blacklisted This transaction has been declined by BLS.',
    '6003' => 'IP Address Blacklisted This transaction has been declined by BLS.',
    '6004' => 'UCI Blacklisted This transaction has been declined by BLS.',
    '6005' => 'GIR Check Failed This transaction has been declined by Global IP Recognition Settings.',
    '6006' => 'IVS Check Failed The fraud module determined that this transaction was not safe for processing. This was determined by the IP Verification Service Procedure.',
    '6007' => 'RFI Check Failed This transaction has been declined by RFI procedures.',
    '6008' => 'RSI Check Failed This transaction has been declined by RSI procedures.',
    '6009' => 'UCI Check Failed This transaction has been declined by UCI procedures.',
    '6999' => 'The fraud module encountered an error during processing.',

    // Validation Response
    '7001' => 'Client Token Required The Client Token is required for all tokenization transactions.',
    '7002' => 'Invalid Client Token The Client Token needs to be in an alphanumeric format with no special characters.',
    '7003' => 'Tokenization Record Not Found No associated card details could be located with the specified token.',
    '7004' => 'Token Deregistered The specified token is set to “deregistered” and cannot be used for processing.',

    // Warning Response
    '8001' => 'Mode was ignored Transaction Mode was Ignored. Refer to Data Element 7',
    '8002' => 'Amount was ignored Transaction Amount was Ignored. Refer to Data Element 9',
    '8003' => 'CCType was ignored Credit Card Type was Ignored. Refer to Data Element 12',
    '8004' => 'CCNumber was ignored Credit Card Number was Ignored. Refer to Data Element 14',
    '8005' => 'CCVNumber was ignored CCV Number was Ignored. Refer to Data Element 16',
    '8006' => 'ExpiryMonth was ignored Expiry Month was ignored. Refer to Data Element 17',
    '8007' => 'ExpiryYear was ignored Expiry Year was ignored. Refer to Data Element 18',
    '8008' => 'Cumulative Transaction Limit Almost Exceeded Cumulative Transaction Limit Almost Exceeded',
    '8009' => 'Transaction Limit Exceeded Transaction Limit has been exceeded.',
    '8010' => 'Cumulative Transaction Limit Exceeded Cumulative Transaction Limit exceeded.',
    '8011' => 'Transaction Index was ignored Transaction Index was ignored. Refer to Data Element 5',
    '8012' => 'Currency was ignored Currency was ignored. Refer to Data Element 10',
    '8013' => 'Account Type was ignored Account Type was ignored. Refer to Data Element 13',
    '8014' => 'Card Holder was ignored Card Holder was ignored. Refer to Data Element 15',
    '8015' => 'Budget was ignored Budget was ignored. Refer to Data Element 19',
    '8016' => 'Budget Period was ignored Budget Period was ignored. Data Element 20',
    '8017' => 'Cashback Amount was ignored Cashback Amount was ignored. Refer to Data Element 11',
    '8018' => 'Authorisation was ignored Authorisation was ignored. Refer to Data Element 11',
    '8019' => 'PIN was ignored',
    '8020' => 'Terminal was ignored',
    '8021' => 'ClientReference was ignored',
    '8022' => 'eCommerceIndicator was ignored',
    '8023' => 'verifiedByVisaXID was ignored',
    '8024' => 'verifiedByVisaCAVV was ignored',
    '8025' => 'secureCodeUCAF was ignored',
    '8026' => 'UCI was ignored',
    '8027' => 'IP Address was ignored',
    '8028' => 'Shipping Country Code was ignored',
    '8029' => 'Flagged for Card Number Blacklist This transaction has been flagged by the Card Number Blacklist Procedure.',
    '8030' => 'Flagged for Country Code Blacklist This transaction has been flagged by the Country Code Blacklist Procedure.',
    '8031' => 'Flagged for IP Address Blacklist This transaction has been flagged by the IP Address Blacklist Procedure.',
    '8032' => 'Flagged for UCI Blacklist This transaction has been flagged by the Unique Client Identifier Blacklist Procedure.',
    '8033' => 'Flagged for GIR This transaction has been flagged by the GIR Procedure.',
    '8034' => 'Flagged for IVS This transaction has been flagged by the IVS Procedure.',
    '8035' => 'Flagged for RFI This transaction has been flagged by the RFI Procedure',
    '8036' => 'Flagged for RSI This transaction has been flagged by the RSI Procedure.',
    '8037' => 'Flagged for UCI This transaction has been flagged by the UCI Procedure.',
    '8038' => 'Card Number Blacklist not performed Card Number Blacklist procedure was not performed on this transaction',
    '8039' => 'Country Code Blacklist not performed Country Code Blacklist procedure was not performed on this transaction.',
    '8040' => 'IP Address Blacklist not performed IP Address Blacklist procedure was not performed on this transaction.',
    '8041' => 'UCI Blacklist not performed Unique Client Identifier Blacklist procedure was not performed on this transaction.',
    '8042' => 'GIR not performed GIR procedure was not performed on this transaction.',
    '8043' => 'IVS not performed IVS procedure was not performed on this transaction.',
    '8044' => 'RFI not performed RFI procedure was not performed on this transaction.',
    '8045' => 'RSI not performed RSI procedure was not performed on this transaction.',
    '8046' => 'UCI not performed UCI procedure was not performed on this transaction.',
    '8047' => 'PurchaseItemsID Was Ignored',

    // Unexpected Error
    '9001' => 'An unexpected error has occurred. Please try again later.',
    '9002' => 'Request Not Implemented You requested functionality that has not been implemented on this gateway yet.',
    '9003' => 'Card Type Not Implemented This card type has not yet been implemented on this gateway.',
    '9004' => 'Fraud Status Unknown The fraud module returned an unexpected status.',
    '9005' => 'Fraud Result Unknown The fraud module returned an unexpected result.',
    '9998' => 'Consummation Error There was an error in the Consummation object.',
    '9999' => 'An internal gateway error has occurred, please try again.'
  ];

}
